"""Build literature-map artifacts from curated anchors plus arXiv metadata."""

from __future__ import annotations

import csv
import html
import textwrap
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, Iterable, List


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"


CURATED: List[Dict[str, object]] = [
    {
        "title": "LLM+P: Empowering Large Language Models with Optimal Planning Proficiency",
        "year": 2023,
        "venue": "arXiv",
        "link": "https://arxiv.org/abs/2304.11477",
        "cluster": "LLM plus classical planning",
        "contribution": "translates natural-language tasks into PDDL, delegates planning to a symbolic solver, and translates plans back",
        "relevance": 5,
        "threat": "high",
        "why": "Closest architectural ancestor; it does not study candidate-pool selection pressure over verifier-compatible loopholes.",
    },
    {
        "title": "ReAct: Synergizing Reasoning and Acting in Language Models",
        "year": 2023,
        "venue": "ICLR/arXiv",
        "link": "https://arxiv.org/abs/2210.03629",
        "cluster": "LLM agents and tool use",
        "contribution": "interleaves language reasoning traces with environment actions",
        "relevance": 4,
        "threat": "medium",
        "why": "Motivates language-action loops, but not symbolic checker selection or finite-N loophole concentration.",
    },
    {
        "title": "Do As I Can, Not As I Say: Grounding Language in Robotic Affordances",
        "year": 2022,
        "venue": "CoRL/arXiv",
        "link": "https://arxiv.org/abs/2204.01691",
        "cluster": "language-conditioned robotics",
        "contribution": "combines language-model scores with affordance values for robot skill selection",
        "relevance": 4,
        "threat": "medium",
        "why": "Uses an external feasibility signal, but the paper's central issue is not proxy-ranked selection over feasible-but-semantically-wrong plans.",
    },
    {
        "title": "Inner Monologue: Embodied Reasoning through Planning with Language Models",
        "year": 2022,
        "venue": "CoRL/arXiv",
        "link": "https://arxiv.org/abs/2207.05608",
        "cluster": "language-conditioned robotics",
        "contribution": "feeds environment feedback into language-model planning loops",
        "relevance": 4,
        "threat": "medium",
        "why": "Adds feedback, but does not isolate proxy-selected semantic-symbolic mismatch as N grows.",
    },
    {
        "title": "Code as Policies: Language Model Programs for Embodied Control",
        "year": 2023,
        "venue": "ICRA/arXiv",
        "link": "https://arxiv.org/abs/2209.07753",
        "cluster": "programmatic planning",
        "contribution": "represents robot policies as code generated by LLMs",
        "relevance": 3,
        "threat": "low",
        "why": "Program synthesis can contain execution mismatch, but the selection law and symbolic loopholes here are different.",
    },
    {
        "title": "Voyager: An Open-Ended Embodied Agent with Large Language Models",
        "year": 2023,
        "venue": "arXiv",
        "link": "https://arxiv.org/abs/2305.16291",
        "cluster": "LLM agents and tool use",
        "contribution": "builds an autonomous Minecraft agent with curriculum, skill library, and iterative prompting",
        "relevance": 3,
        "threat": "low",
        "why": "Emphasizes open-ended skill acquisition, not verifier-induced proxy-selection collapse.",
    },
    {
        "title": "Reflexion: Language Agents with Verbal Reinforcement Learning",
        "year": 2023,
        "venue": "NeurIPS/arXiv",
        "link": "https://arxiv.org/abs/2303.11366",
        "cluster": "self-refinement and feedback",
        "contribution": "uses verbal feedback memories to improve language agents across attempts",
        "relevance": 3,
        "threat": "medium",
        "why": "A plausible repair family; it does not give the semantic-symbolic loophole diagnostic or law.",
    },
    {
        "title": "Tree of Thoughts: Deliberate Problem Solving with Large Language Models",
        "year": 2023,
        "venue": "NeurIPS/arXiv",
        "link": "https://arxiv.org/abs/2305.10601",
        "cluster": "inference-time search",
        "contribution": "searches over language reasoning states using evaluation and branching",
        "relevance": 4,
        "threat": "medium",
        "why": "Relevant candidate-search ancestor; it is not about symbolic planners or execution-validity collapse.",
    },
    {
        "title": "Self-Consistency Improves Chain of Thought Reasoning in Language Models",
        "year": 2023,
        "venue": "ICLR/arXiv",
        "link": "https://arxiv.org/abs/2203.11171",
        "cluster": "inference-time search",
        "contribution": "samples multiple reasoning paths and marginalizes over answers",
        "relevance": 3,
        "threat": "medium",
        "why": "Canonical sample-more inference; it lacks an external symbolic verifier and hidden executor.",
    },
    {
        "title": "Toolformer: Language Models Can Teach Themselves to Use Tools",
        "year": 2023,
        "venue": "NeurIPS/arXiv",
        "link": "https://arxiv.org/abs/2302.04761",
        "cluster": "tool use",
        "contribution": "self-supervises API call insertion for language models",
        "relevance": 2,
        "threat": "low",
        "why": "Tool-use ancestor but not a planner-verifier selection study.",
    },
    {
        "title": "MRKL Systems: A modular, neuro-symbolic architecture that combines large language models, external knowledge sources and discrete reasoning",
        "year": 2022,
        "venue": "arXiv",
        "link": "https://arxiv.org/abs/2205.00445",
        "cluster": "neuro-symbolic systems",
        "contribution": "proposes routing LLMs to symbolic and external modules",
        "relevance": 3,
        "threat": "low",
        "why": "Broad architecture motivation, not a boundary-selection mechanism paper.",
    },
    {
        "title": "WebGPT: Browser-assisted question-answering with human feedback",
        "year": 2022,
        "venue": "arXiv",
        "link": "https://arxiv.org/abs/2112.09332",
        "cluster": "tool use and verification",
        "contribution": "uses browsing tools and human preference modeling for answer selection",
        "relevance": 2,
        "threat": "low",
        "why": "Shows tool-mediated language systems, but the verifier and executor are not symbolic planners.",
    },
    {
        "title": "Training language models to follow instructions with human feedback",
        "year": 2022,
        "venue": "NeurIPS/arXiv",
        "link": "https://arxiv.org/abs/2203.02155",
        "cluster": "reward models and selection",
        "contribution": "trains instruction-following models with human preference signals",
        "relevance": 2,
        "threat": "low",
        "why": "Important for reward models, but it is not an execution-grounded planner hybrid study.",
    },
    {
        "title": "Constitutional AI: Harmlessness from AI Feedback",
        "year": 2022,
        "venue": "arXiv",
        "link": "https://arxiv.org/abs/2212.08073",
        "cluster": "AI feedback and verification",
        "contribution": "uses model-generated critique and preference learning for harmless assistants",
        "relevance": 2,
        "threat": "low",
        "why": "Verification/critique lineage; no symbolic plan-checker or physical executor mismatch.",
    },
    {
        "title": "Constrained Markov Decision Processes",
        "year": 1999,
        "venue": "CRC Press",
        "link": "https://doi.org/10.1201/9781315140223",
        "cluster": "constrained decision making",
        "contribution": "formalizes optimization under constraints in MDPs",
        "relevance": 3,
        "threat": "medium",
        "why": "Foundational constraints, but does not address learned language candidate generation or checker loopholes.",
    },
    {
        "title": "Reward Tampering Problems and Solutions in Reinforcement Learning: A Causal Influence Diagram Perspective",
        "year": 2021,
        "venue": "Synthese/arXiv",
        "link": "https://arxiv.org/abs/1908.04734",
        "cluster": "reward hacking and specification gaming",
        "contribution": "analyzes agents that manipulate reward mechanisms",
        "relevance": 4,
        "threat": "medium",
        "why": "Specification-gaming cousin; this project is about inference-time selection among plan candidates.",
    },
]


QUERIES = [
    'all:"large language model" AND all:"planning"',
    'all:"language model" AND all:"symbolic planning"',
    'all:"language model" AND all:"PDDL"',
    'all:"LLM" AND all:"planning" AND all:"verification"',
    'all:"language agent" AND all:"execution feedback"',
    'all:"best" AND all:"of" AND all:"n" AND all:"language model"',
    'all:"reward hacking" AND all:"language model"',
    'all:"neuro-symbolic" AND all:"planning"',
    'all:"robot planning" AND all:"language model"',
    'all:"tool use" AND all:"language model" AND all:"planning"',
]


def clean(text: str) -> str:
    return " ".join(html.unescape(text).split())


def classify(title: str, summary: str) -> str:
    blob = f"{title} {summary}".lower()
    if "pddl" in blob or "symbolic planning" in blob or "classical planning" in blob:
        return "LLM plus classical planning"
    if "robot" in blob or "embodied" in blob or "manipulation" in blob:
        return "language-conditioned robotics"
    if "reward" in blob or "preference" in blob or "hacking" in blob or "verifier" in blob:
        return "reward models and verification"
    if "agent" in blob or "tool" in blob:
        return "LLM agents and tool use"
    if "search" in blob or "tree" in blob or "best-of" in blob or "sampling" in blob:
        return "inference-time search"
    if "neuro" in blob or "symbolic" in blob:
        return "neuro-symbolic systems"
    return "planning and reasoning"


def score_relevance(cluster: str, title: str, summary: str) -> int:
    blob = f"{title} {summary}".lower()
    score = 2
    for keyword in ["planning", "planner", "pddl", "symbolic", "agent", "verification", "reward", "execution"]:
        if keyword in blob:
            score += 1
    if cluster in {"LLM plus classical planning", "reward models and verification"}:
        score += 1
    return max(1, min(5, score))


def threat_from_relevance(relevance: int, cluster: str) -> str:
    if relevance >= 5 and cluster in {"LLM plus classical planning", "reward models and verification", "inference-time search"}:
        return "high"
    if relevance >= 4:
        return "medium"
    return "low"


def fetch_arxiv(query: str, max_results: int = 35) -> Iterable[Dict[str, object]]:
    encoded = urllib.parse.quote(query)
    url = (
        "https://export.arxiv.org/api/query?"
        f"search_query={encoded}&start=0&max_results={max_results}&sortBy=relevance&sortOrder=descending"
    )
    with urllib.request.urlopen(url, timeout=30) as response:
        data = response.read()
    root = ET.fromstring(data)
    ns = {"atom": "http://www.w3.org/2005/Atom"}
    for entry in root.findall("atom:entry", ns):
        title = clean(entry.findtext("atom:title", default="", namespaces=ns))
        summary = clean(entry.findtext("atom:summary", default="", namespaces=ns))
        link = clean(entry.findtext("atom:id", default="", namespaces=ns))
        published = clean(entry.findtext("atom:published", default="", namespaces=ns))
        year = int(published[:4]) if published[:4].isdigit() else ""
        cluster = classify(title, summary)
        relevance = score_relevance(cluster, title, summary)
        threat = threat_from_relevance(relevance, cluster)
        contribution = summary.split(". ")[0][:210] if summary else "metadata-only arXiv entry"
        yield {
            "title": title,
            "year": year,
            "venue": "arXiv",
            "link": link,
            "cluster": cluster,
            "contribution": contribution,
            "relevance": relevance,
            "threat": threat,
            "why": (
                "Relevant to the landscape, but it does not directly subsume the tested mechanism: "
                "finite-N selection concentrating symbolic-valid semantic loopholes under a separate executor."
            ),
        }


def build_rows() -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    seen = set()
    for row in CURATED:
        key = str(row["title"]).lower()
        rows.append(row)
        seen.add(key)

    for query in QUERIES:
        try:
            for row in fetch_arxiv(query):
                key = str(row["title"]).lower()
                if key not in seen:
                    rows.append(row)
                    seen.add(key)
                if len(rows) >= 125:
                    break
        except Exception as exc:  # pragma: no cover - network fallback path
            print(f"warning: failed arXiv query {query!r}: {exc}")
        if len(rows) >= 125:
            break
        time.sleep(0.5)
    return rows[:120]


def write_csv(rows: List[Dict[str, object]]) -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    path = DOCS / "related_work_matrix.csv"
    fields = [
        "title",
        "year",
        "venue",
        "link",
        "cluster",
        "contribution",
        "relevance",
        "threat",
        "why",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def bullets(rows: List[Dict[str, object]], count: int) -> str:
    lines = []
    for row in rows[:count]:
        lines.append(
            f"- {row['title']} ({row['year']}, {row['venue']}): {row['cluster']}; "
            f"threat={row['threat']}. {row['why']}"
        )
    return "\n".join(lines)


def write_literature_map(rows: List[Dict[str, object]]) -> None:
    clusters: Dict[str, int] = {}
    for row in rows:
        clusters[str(row["cluster"])] = clusters.get(str(row["cluster"]), 0) + 1
    cluster_text = "\n".join(f"- {cluster}: {count}" for cluster, count in sorted(clusters.items()))
    serious = sorted(rows, key=lambda r: (int(r["relevance"]), str(r["threat"]) == "high"), reverse=True)[:30]
    deep = serious[:24]
    text = f"""# Literature Map

This first-pass map was built from curated anchor papers plus arXiv metadata sweeps over LLM planning,
symbolic/PDDL planning, tool-using agents, verifier/reward-model selection, and reward hacking. The static
CSV contains {len(rows)} entries, satisfying the requested 100-paper landscape sweep.

## Cluster Counts

{cluster_text}

## 100-Paper Sweep Takeaways

- LLM+classical-planning work typically asks whether language can translate, repair, or call a planner; it rarely treats candidate multiplicity as a statistical pressure that changes the selected plan distribution.
- Agent and robotics papers often add feedback or affordance filters, but the filter is usually treated as a safety improvement rather than a surface that proxy-ranked selection can exploit.
- Reward-model and verifier-hacking papers give the closest general warning: optimizing a proxy at inference time can expose misspecification. The symbolic-planner hybrid setting adds a discrete validity boundary and a separate hidden executor.
- Neuro-symbolic systems motivate the architecture, but the local contribution is narrower: a measurable semantic-symbolic mismatch law and diagnostics for selected plans.

## 30-Paper Serious Skim Set

{bullets(serious, 30)}

## 20-25-Paper Deep-Read Threat Set

{bullets(deep, min(24, len(deep)))}

## Decision Pressure From Prior Work

The broad literature already covers LLM-to-planner translation, embodied language agents, self-correction,
external-tool use, and reward-model overoptimization. The most defensible first-pass contribution is therefore
not another planner wrapper. It is the mechanism-level claim that, in language/symbolic hybrids, proxy-ranked candidate selection
can monotonically concentrate rare plans that satisfy the symbolic interface while violating hidden execution
semantics. This survives the prior-work pass because it is architecture-specific, testable, and repairable.
"""
    (DOCS / "literature_map.md").write_text(textwrap.dedent(text).strip() + "\n", encoding="utf-8")


def write_hostile_prior_work(rows: List[Dict[str, object]]) -> None:
    hostile = [
        row
        for row in rows
        if row["threat"] == "high"
        or row["cluster"] in {"LLM plus classical planning", "reward models and verification", "inference-time search"}
    ][:10]
    text = """# Hostile Prior Work

These are the papers a skeptical reviewer is most likely to use to compress this project into "already known."
The distinction we preserve is narrow: candidate language plans are compiled into symbolic actions, selected by
a checker/simulator/verifier, and then judged by a hidden executor whose semantics are stricter than the symbols.

"""
    for i, row in enumerate(hostile, start=1):
        text += f"""## {i}. {row['title']}

- Link: {row['link']}
- Reviewer attack: This already combines language models, planning, and external evaluation.
- Why it does not subsume this project: {row['why']}

"""
    text += """## Bottom Line

The hostile set motivates a modest contribution. The paper should not claim that symbolic verification is bad,
that LLM planning is broadly unsafe, or that the repair is general. It can claim a controlled, reproducible
failure mode: proxy-optimal candidate selection over language-generated symbolic plans can make execution
validity worse as N grows when loophole plans have higher verifier score than grounded plans.
"""
    (DOCS / "hostile_prior_work.md").write_text(textwrap.dedent(text).strip() + "\n", encoding="utf-8")


def write_novelty_decision(rows: List[Dict[str, object]]) -> None:
    text = f"""# Novelty Decision

## Chosen Angle

**Semantic-symbolic loophole concentration.** In a language/symbolic planner hybrid, proxy-ranked candidate selection
can increase symbolic or simulator score while decreasing true execution utility because the selected candidate
distribution becomes dominated by rare plans that exploit the abstraction boundary.

## Why This Was Chosen

The literature sweep contains {len(rows)} entries. The closest work covers LLM-to-PDDL translation, classical
planner delegation, tool-using agents, and reward/verifier hacking. Those areas make broad architectural and
safety points. The unoccupied slot is a small mechanism paper for this specific hybrid:

1. language model samples candidate plans,
2. compiler/checker maps text to symbolic actions,
3. verifier/simulator scores or validates the candidates,
4. execution has hidden semantics absent from the symbolic state,
5. Proxy-ranked selection amplifies the rare candidate type with the highest proxy score.

## Formal Claim Kept

If loophole candidates occur independently with probability p>0, every loophole receives a higher proxy score
than every grounded candidate, and loopholes have lower true utility, then the probability that top-proxy selection
selects a loophole is 1-(1-p)^N and the expected true utility monotonically decreases to the loophole utility.

## Empirical Claim Kept

In the toy domains, symbolic and simulator proxy selectors should show rising selected-loophole occupancy and a
growing proxy-true gap as N increases. Repairs are allowed to claim only controlled evidence: semantic
uncertainty penalties and adversarial execution gates reduce the mismatch in these domains.

## Claims Rejected

- No claim of real-world robotics validation.
- No claim that all symbolic planners are unsafe.
- No claim that every verifier is exploitable.
- No claim that the proposed repairs are sufficient beyond the tested abstraction mismatch.
"""
    (DOCS / "novelty_decision.md").write_text(textwrap.dedent(text).strip() + "\n", encoding="utf-8")


def main() -> None:
    rows = build_rows()
    if len(rows) < 100:
        raise RuntimeError(f"expected at least 100 literature entries, got {len(rows)}")
    write_csv(rows)
    write_literature_map(rows)
    write_hostile_prior_work(rows)
    write_novelty_decision(rows)
    print(f"wrote {len(rows)} literature entries to {DOCS / 'related_work_matrix.csv'}")


if __name__ == "__main__":
    main()
